@startuml

Tree o-- Node : tiene >
Tree o-- InsertionStrategy : usa >

InsertionStrategy <|.. NormalBSTStrategy
InsertionStrategy <|.. BalancedStrategy
InsertionStrategy <|.. InvertedBSTStrategy

Jardinero ..> Tree : usa
Jardinero ..> InsertionStrategy : usa

@enduml