@startuml

object "jardinero:Jardinero" as jardinero

object "normalTree:Tree" as tree1 
object "balancedTree:Tree" as tree2 
object "invertedTree:Tree" as tree3 

object "strategy1:NormalBSTStrategy" as strat1
object "strategy2:BalancedStrategy" as strat2
object "strategy3:InvertedBSTStrategy" as strat3

object "node1_1:Node" as n1_1 {
    value = 2
}
object "node1_2:Node" as n1_2 {
    value = 1
}
object "node1_3:Node" as n1_3 {
    value = 6
}
object "node1_4:Node" as n1_4 {
    value = 5
}
object "node1_5:Node" as n1_5 {
    value = 7
}
object "node1_6:Node" as n1_6 {
    value = 3
}
object "node1_7:Node" as n1_7 {
    value = 9
}
object "node1_8:Node" as n1_8 {
    value = 10
}

' Nodes for balancedTree
object "node2_1:Node" as n2_1 {
    value = 2
}
object "node2_2:Node" as n2_2 {
    value = 6
}
object "node2_3:Node" as n2_3 {
    value = 5
}
object "node2_4:Node" as n2_4 {
    value = 3
}
object "node2_5:Node" as n2_5 {
    value = 7
}
object "node2_6:Node" as n2_6 {
    value = 1
}
object "node2_7:Node" as n2_7 {
    value = 9
}
object "node2_8:Node" as n2_8 {
    value = 10
}

' Nodes for invertedTree
object "node3_1:Node" as n3_1 {
    value = 2
}
object "node3_2:Node" as n3_2 {
    value = 6
}
object "node3_3:Node" as n3_3 {
    value = 1
}
object "node3_4:Node" as n3_4 {
    value = 7
}
object "node3_5:Node" as n3_5 {
    value = 5
}
object "node3_6:Node" as n3_6 {
    value = 9
}
object "node3_7:Node" as n3_7 {
    value = 3
}
object "node3_8:Node" as n3_8 {
    value = 10
}

' Relationships
jardinero ..> tree1
jardinero ..> tree2
jardinero ..> tree3

tree1 --> strat1 : strategy
tree2 --> strat2 : strategy
tree3 --> strat3 : strategy

' Normal tree structure
tree1 --> n1_1 : root
n1_1 --> n1_2 : left
n1_1 --> n1_3 : right
n1_3 --> n1_4 : left
n1_4 --> n1_6 : left
n1_3 --> n1_5 : right
n1_5 --> n1_7 : right
n1_7 --> n1_8 : right

' Balanced tree structure
tree2 --> n2_1 : root
n2_1 --> n2_2 : left
n2_2 --> n2_4 : left
n2_2 --> n2_6 : right
n2_1 --> n2_3 : right
n2_3 --> n2_5 : left
n2_3 --> n2_7 : right
n2_7 --> n2_8 : right

' Inverted tree structure
tree3 --> n3_1 : root
n3_1 --> n3_2 : left
n3_2 --> n3_4 : left
n3_4 --> n3_6 : left
n3_6 --> n3_8 : left
n3_2 --> n3_5 : right
n3_5 --> n3_7 : right
n3_1 --> n3_3 : right

note right of jardinero
  Cada árbol mantiene su propia
  estructura según su estrategia
  de inserción
end note
@enduml
@enduml