@startuml
class Biblioteca {
}

class Libro {
  +Título: String
  +ISBN: String
  +Año: Integer
}

class Usuario {
  +Nombre: String
  +ID: Integer
  +Membresía: String
}

class Autor {
  +Nombre: String
}

class Préstamo {
  +FechaInicio: Date
  +FechaFin: Date
}

class Categoría {
  +Nombre: String
}

Biblioteca "1" -- "0..*" Libro 
Biblioteca "1" -- "0..*" Usuario 
Libro "1" -- "0..*" Autor 
Libro "1" -- "0..*" Categoría
Usuario "1" -- "0..*" Préstamo
Préstamo "1" -- "1" Libro
Préstamo "1" -- "1" Usuario
@enduml
